### ISSUE TITLE
Dataman functions don't have an arg for database

### ISSUE THREAD

**Issue by jacksontj** [ghowland/yudien#25]
Right now `__data_get` etc. all take a collection name, but when using this in a sufficiently complex system we'll want to support N DBs. Presumably we'd configure the dataman clients as a map of them with a default, as an example:

```
dataman_clients:
- name: opsdb
  default: true
  opts: <some opts>
- name: web6
  opts: <some other opts>
```

This would allow yudien's access of data to span databases
